/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_thobe_frame_Frame */

#ifndef _Included_org_thobe_frame_Frame
#define _Included_org_thobe_frame_Frame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_thobe_frame_Frame
 * Method:    buildFrame
 * Signature: (I)Lorg/thobe/frame/Frame;
 */
JNIEXPORT jobject JNICALL Java_org_thobe_frame_Frame_buildFrame
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_thobe_frame_Frame
 * Method:    buildStackTraceFrames
 * Signature: (I)[Lorg/thobe/frame/Frame;
 */
JNIEXPORT jobjectArray JNICALL Java_org_thobe_frame_Frame_buildStackTraceFrames
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_thobe_frame_Frame
 * Method:    setupNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_thobe_frame_Frame_setupNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_thobe_frame_Frame_LocalVariable */

#ifndef _Included_org_thobe_frame_Frame_LocalVariable
#define _Included_org_thobe_frame_Frame_LocalVariable
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_thobe_frame_Frame_ThreadFrames */

#ifndef _Included_org_thobe_frame_Frame_ThreadFrames
#define _Included_org_thobe_frame_Frame_ThreadFrames
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_thobe_frame_Frame_ThreadFrames
 * Method:    buildStackTraceFrames
 * Signature: (I)[Lorg/thobe/frame/Frame/ThreadFrames;
 */
JNIEXPORT jobjectArray JNICALL Java_org_thobe_frame_Frame_00024ThreadFrames_buildStackTraceFrames
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_thobe_frame_Frame_ThreadFrames
 * Method:    buildStackTraceFramesFor
 * Signature: ([Ljava/lang/Thread;I)[Lorg/thobe/frame/Frame/ThreadFrames;
 */
JNIEXPORT jobjectArray JNICALL Java_org_thobe_frame_Frame_00024ThreadFrames_buildStackTraceFramesFor
  (JNIEnv *, jclass, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
